### PR TITLE
fix redundencies in go language

### PR DESCRIPTION
**Pull request by 1whatleytay**

### CODE REVIEW

**Comment by AadityaChaudhary** [comment]
No description included. Please explain the changes made in the PR, and open another

**Comment by yashmulki** [comment]
Please rewrite this in the node.js language

**Comment by yashmulki** [comment]
please also python

**Comment by AadityaChaudhary** [comment]
Please Leave me alone

**Comment by yashmulki** [comment]
python is the best

**Comment by yashmulki** [comment]
yash trivedi codes in python

**Comment by yashmulki** [comment]
he does opencv machine learning and django

**Comment by yashmulki** [comment]
objective proof that it is the best

**Pull request closed without merging**
